#!/bin/bash

echo "INSTALLING dotfiles for DevX Spaces!"

DOTFILES_ROOT="/root/dotfiles-BLP"
LN=/bin/ln
MV=/bin/mv
YUM=/bin/yum

${YUM} install -y git vim wget curl

${LN} -s ~/dotfiles-BLP/vim8_dir ~/.vim
cd ${DOTFILES_ROOT}
git submodule init
git submodule update

# vim "+PackUpdate" "+q" "+:q"

${LN} -s ~/dotfiles-BLP/kshrc ~/.kshrc
${MV} ~/.bashrc ~/.bashrc-BAD
${LN} -s ~/dotfiles-BLP/bashrc ~/.bashrc

cd

# Set up Rust/Aya dev environment
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
mkdir ~/.cargo
cp ~/dotfiles-BLP/cargo-config.toml ~/.cargo/config.toml
cat << EOF >> ~/.gitconfig

[http "https://crates.dev.bloomberg.com/"]
    proxy = http://bproxy.tdmz1.bloomberg.com:80
EOF
